### ISSUE TITLE
Change file encodings to UTF-8

### ISSUE THREAD

**Issue by ghost** [r57zone/Podcast-Easy-for-python#2]
You need to change script encoding to UTF-8, because GitHub supports only UTF-8 encoding.

**Comment by r57zone** [comment]
Python IDLE default displays UTF-8 is not correctly.

**Comment by ghost** [comment]
You don't need to use Python IDLE, use Notepad++ instead

**Comment by ghost** [comment]
How long it will take to fix UTF-8?

**Comment by ghost** [comment]
@r57zone why close?

**Comment by r57zone** [comment]
I do not plan to fix this problem, maybe later, reopened.

**Comment by TiberiumPY** [comment]
@r57zone Do you understand, that your code isn't the best-looking? It's very bad coding style.

**Comment by ghost** [comment]
@r57zone I'll refactor Python 3 version right now.

**Comment by r57zone** [comment]
Podcast Easy updated, now only in English. The files are encoded with UTF-8.
